name: my_first_app
description: "A flutter chat application."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Added packages
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true